//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosTorresFerreterosSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPrestamo
    {
        public int codigo { get; set; }
        public int cantidad { get; set; }
        public int valor_unitario { get; set; }
        public string fecha_retorno { get; set; }
        public Nullable<decimal> porcentaje_descuento { get; set; }
        public decimal porcentaje_iva { get; set; }
        public bool retornado { get; set; }
        public int id_producto { get; set; }
        public int id_prestamo { get; set; }

        [JsonIgnore]
        public virtual Producto Producto { get; set; }
        [JsonIgnore]
        public virtual Prestamo Prestamo { get; set; }
    }
}
