//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosTorresFerreterosSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Clientes = new HashSet<Cliente>();
            this.Empleado1 = new HashSet<Empleado>();
            this.Prestamoes = new HashSet<Prestamo>();
            this.Productoes = new HashSet<Producto>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public int numero_documento { get; set; }
        public string numero_telefono { get; set; }
        public string direccion { get; set; }
        public string fecha_nacimiento { get; set; }
        public int salario { get; set; }
        public bool activo { get; set; }
        public bool es_usuario { get; set; }
        public int id_empleado { get; set; }
        public int id_cargo { get; set; }
        public int id_genero { get; set; }
        public int id_tipodocumento { get; set; }
        public int id_ciudad { get; set; }

        [JsonIgnore]
        public virtual Cargo Cargo { get; set; }
        [JsonIgnore]
        public virtual Ciudad Ciudad { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        [JsonIgnore]
        public virtual Empleado Empleado2 { get; set; }
        [JsonIgnore]
        public virtual Genero Genero { get; set; }
        [JsonIgnore]
        public virtual TipoDocumento TipoDocumento { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamoes { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productoes { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
