//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosTorresFerreterosSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetallesPrestamoes = new HashSet<DetallesPrestamo>();
        }
    
        public int codigo { get; set; }
        public int existencia { get; set; }
        public int valor_dia { get; set; }
        public string descripcion { get; set; }
        public string caracteristicas { get; set; }
        public bool activo { get; set; }
        public int id_tipoproducto { get; set; }
        public int id_marca { get; set; }
        public int id_empleado { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPrestamo> DetallesPrestamoes { get; set; }
        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual Marca Marca { get; set; }
        [JsonIgnore]
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
