//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosTorresFerreterosSAS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public int codigo { get; set; }
        public string direccion { get; set; }
        public bool activo { get; set; }
        public int id_ciudad { get; set; }
        public int id_cliente { get; set; }

        [JsonIgnore]
        public virtual Ciudad Ciudad { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
    }
}
